// 由 Source/gen_csharp_data.py 生成,勿手改。
namespace HSKTraitExt
{
    public static class HSKData
    {
        public struct LifestyleRule
        {
            public string Key, TriggerType, TriggerTarget;
            public int PosThreshold, PosDegree; public string PosTrait;
            public int NegThreshold, NegDegree; public string NegTrait;
            public int CooldownDays;
            public float Chance; // 达标后授予概率(0~1), 默认0.1=原100%降10倍; 毒品类0.25
        }
        public static readonly LifestyleRule[] LifestyleRules = new LifestyleRule[]
        {
            new LifestyleRule{ Key="园艺", TriggerType="Plant", TriggerTarget="", PosThreshold=240, PosTrait="BrownThumb", PosDegree=1, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="屠宰", TriggerType="Job", TriggerTarget="ButcherCorpse", PosThreshold=80, PosTrait="Butcher", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="看电视", TriggerType="JoyKind", TriggerTarget="Television", PosThreshold=480, PosTrait="VTE_CouchPotato", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="饮酒", TriggerType="Drug", TriggerTarget="Alcohol", PosThreshold=200, PosTrait="VTE_Lush", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.06f },
            new LifestyleRule{ Key="吸烟", TriggerType="Drug", TriggerTarget="Smokeleaf", PosThreshold=200, PosTrait="VTE_Stoner", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.06f },
            new LifestyleRule{ Key="药物滥用", TriggerType="Drug", TriggerTarget="Other", PosThreshold=200, PosTrait="DrugDesire", PosDegree=1, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.06f },
            new LifestyleRule{ Key="制药/化学", TriggerType="Job", TriggerTarget="DoBills", PosThreshold=80, PosTrait="Chemist", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="烹饪", TriggerType="Job", TriggerTarget="CookFood", PosThreshold=160, PosTrait="Gourmet", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="研究", TriggerType="Job", TriggerTarget="Research", PosThreshold=60, PosTrait="Inventor", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="医疗", TriggerType="Job", TriggerTarget="TendPatient", PosThreshold=80, PosTrait="Medic", PosDegree=1, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="手工/工匠", TriggerType="Job", TriggerTarget="SmithWeapon", PosThreshold=100, PosTrait="Perfectionist", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="清洁/整洁", TriggerType="Job", TriggerTarget="Clean", PosThreshold=80, PosTrait="NeatFreak", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="建造", TriggerType="WorkType", TriggerTarget="Construction", PosThreshold=100, PosTrait="VTE_Groundbreaker", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="岩矿", TriggerType="Job", TriggerTarget="Mine", PosThreshold=120, PosTrait="Rockhound", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="近战", TriggerType="Job", TriggerTarget="AttackMelee", PosThreshold=80, PosTrait="VTE_MartialArtist", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="闪避/肉搏", TriggerType="Job", TriggerTarget="AttackMelee", PosThreshold=80, PosTrait="Dodging", PosDegree=1, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="射击", TriggerType="Job", TriggerTarget="AttackRanged", PosThreshold=100, PosTrait="ShootingAccuracy", PosDegree=1, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="击杀人类", TriggerType="Kill", TriggerTarget="Humanlike", PosThreshold=25, PosTrait="Bloodlust", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="残忍手术", TriggerType="Job", TriggerTarget="DoSurgery", PosThreshold=40, PosTrait="VTE_MadSurgeon", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="情爱", TriggerType="Job", TriggerTarget="Lovin", PosThreshold=40, PosTrait="VTE_Insatiable", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="社交闲聊", TriggerType="Job", TriggerTarget="SocialRelax", PosThreshold=100, PosTrait="Kind", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="商贸/谈判", TriggerType="Job", TriggerTarget="Trade", PosThreshold=60, PosTrait="Trader", PosDegree=1, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="外交", TriggerType="Job", TriggerTarget="Negotiate", PosThreshold=60, PosTrait="Diplomat", PosDegree=1, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="动物", TriggerType="Job", TriggerTarget="Tame", PosThreshold=80, PosTrait="VTE_AnimalLover", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="动物虐待", TriggerType="AbuseAnimal", TriggerTarget="", PosThreshold=40, PosTrait="VTE_AnimalHater", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.02f },
            new LifestyleRule{ Key="偷窃", TriggerType="Job", TriggerTarget="Steal", PosThreshold=60, PosTrait="VTE_Kleptomaniac", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.02f },
            new LifestyleRule{ Key="餐饮讲究", TriggerType="Eat", TriggerTarget="", PosThreshold=100, PosTrait="Gourmet", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="战后创伤", TriggerType="None", TriggerTarget="", PosThreshold=20, PosTrait="VTE_Desensitized", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.03f },
            new LifestyleRule{ Key="耐痛/战场", TriggerType="None", TriggerTarget="", PosThreshold=30, PosTrait="PainThreshold", PosDegree=1, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.04f },
            new LifestyleRule{ Key="体质抗病", TriggerType="None", TriggerTarget="", PosThreshold=0, PosTrait="Constitution", PosDegree=1, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="温度-耐热", TriggerType="TempHot", TriggerTarget="", PosThreshold=160, PosTrait="HeatLover", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="温度-耐寒", TriggerType="TempCold", TriggerTarget="", PosThreshold=160, PosTrait="ColdLover", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="进食习惯", TriggerType="Eat", TriggerTarget="", PosThreshold=100, PosTrait="EatingSpeed", PosDegree=1, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="孤独倾向", TriggerType="None", TriggerTarget="", PosThreshold=120, PosTrait="Recluse", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="压力崩溃", TriggerType="MentalBreak", TriggerTarget="", PosThreshold=0, PosTrait="", PosDegree=0, NegThreshold=48, NegTrait="VTE_WorldWeary", NegDegree=0, CooldownDays=365, Chance=0.02f },
            new LifestyleRule{ Key="唯美追求", TriggerType="WorkType", TriggerTarget="Art", PosThreshold=80, PosTrait="Aesthete", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="作息-夜行", TriggerType="Night", TriggerTarget="", PosThreshold=240, PosTrait="HSK_NightOwl", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="作息-晨行", TriggerType="Dawn", TriggerTarget="", PosThreshold=240, PosTrait="HSK_EarlyRiser", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="阅读", TriggerType="Job", TriggerTarget="ReadBook", PosThreshold=100, PosTrait="HSK_Bookworm", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="音乐演奏", TriggerType="Job", TriggerTarget="PlayMusic", PosThreshold=120, PosTrait="HSK_Musician", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="健身", TriggerType="Job", TriggerTarget="Workout", PosThreshold=160, PosTrait="HSK_GymRat", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="冥想", TriggerType="Job", TriggerTarget="Meditate", PosThreshold=100, PosTrait="HSK_Meditator", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="棋牌", TriggerType="Job", TriggerTarget="PlayBilliards", PosThreshold=120, PosTrait="HSK_Tactician", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="饮食健康", TriggerType="Eat", TriggerTarget="", PosThreshold=120, PosTrait="HSK_HealthNut", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.05f },
            new LifestyleRule{ Key="饮食放纵", TriggerType="None", TriggerTarget="", PosThreshold=0, PosTrait="HSK_Glutton", PosDegree=0, NegThreshold=0, NegTrait="", NegDegree=0, CooldownDays=365, Chance=0.02f },
        };
        public struct DomainRow { public string Domain, TraitDef, Coupling; public int Weight; }
        public static readonly DomainRow[] DomainPool = new DomainRow[]
        {
            new DomainRow{ Domain="Combat", TraitDef="VTE_Brave", Weight=3, Coupling="Melee" },
            new DomainRow{ Domain="Combat", TraitDef="Tough", Weight=3, Coupling="Melee" },
            new DomainRow{ Domain="Combat", TraitDef="VTE_ThickSkinned", Weight=2, Coupling="Melee" },
            new DomainRow{ Domain="Combat", TraitDef="VTE_MartialArtist", Weight=2, Coupling="Melee" },
            new DomainRow{ Domain="Combat", TraitDef="VTE_IronStomach", Weight=1, Coupling="Plants" },
            new DomainRow{ Domain="Combat", TraitDef="VTE_DrunkenMaster", Weight=1, Coupling="Melee" },
            new DomainRow{ Domain="Combat", TraitDef="ShootingAccuracy", Weight=3, Coupling="Shooting" },
            new DomainRow{ Domain="Combat", TraitDef="PainThreshold", Weight=2, Coupling="Melee" },
            new DomainRow{ Domain="Combat", TraitDef="Dodging", Weight=2, Coupling="Melee" },
            new DomainRow{ Domain="Combat", TraitDef="VTE_Coward", Weight=2, Coupling="Shooting" },
            new DomainRow{ Domain="Combat", TraitDef="VTE_Clumsy", Weight=2, Coupling="Melee" },
            new DomainRow{ Domain="Combat", TraitDef="Wimp", Weight=1, Coupling="Melee" },
            new DomainRow{ Domain="Social", TraitDef="Kind", Weight=3, Coupling="Social" },
            new DomainRow{ Domain="Social", TraitDef="VTE_Tycoon", Weight=2, Coupling="Social" },
            new DomainRow{ Domain="Social", TraitDef="VTE_Snob", Weight=2, Coupling="Social" },
            new DomainRow{ Domain="Social", TraitDef="Trader", Weight=2, Coupling="Social" },
            new DomainRow{ Domain="Social", TraitDef="Diplomat", Weight=2, Coupling="Social" },
            new DomainRow{ Domain="Social", TraitDef="VTE_Vengeful", Weight=2, Coupling="Social" },
            new DomainRow{ Domain="Social", TraitDef="VTE_Anxious", Weight=2, Coupling="Social" },
            new DomainRow{ Domain="Social", TraitDef="AnnoyingVoice", Weight=1, Coupling="Social" },
            new DomainRow{ Domain="Social", TraitDef="Jealous", Weight=1, Coupling="Social" },
            new DomainRow{ Domain="Faith", TraitDef="Faith", Weight=4, Coupling="Faith" },
            new DomainRow{ Domain="Faith", TraitDef="Occultist", Weight=2, Coupling="Psy" },
            new DomainRow{ Domain="Love", TraitDef="VTE_Insatiable", Weight=2, Coupling="Social" },
            new DomainRow{ Domain="Love", TraitDef="VTE_Prude", Weight=2, Coupling="Social" },
            new DomainRow{ Domain="Love", TraitDef="VTE_FunLoving", Weight=2, Coupling="Social" },
            new DomainRow{ Domain="Love", TraitDef="VTE_Wanderlust", Weight=1, Coupling="Social" },
            new DomainRow{ Domain="Work", TraitDef="VTE_Prodigy", Weight=3, Coupling="Research" },
            new DomainRow{ Domain="Work", TraitDef="Inventor", Weight=3, Coupling="Research" },
            new DomainRow{ Domain="Work", TraitDef="VTE_Workaholic", Weight=3, Coupling="Crafting" },
            new DomainRow{ Domain="Work", TraitDef="Industriousness", Weight=4, Coupling="Global" },
            new DomainRow{ Domain="Work", TraitDef="Perfectionist", Weight=2, Coupling="Crafting" },
            new DomainRow{ Domain="Work", TraitDef="Chemist", Weight=2, Coupling="Crafting" },
            new DomainRow{ Domain="Work", TraitDef="Gourmet", Weight=3, Coupling="Cooking" },
            new DomainRow{ Domain="Work", TraitDef="Medic", Weight=3, Coupling="Medicine" },
            new DomainRow{ Domain="Work", TraitDef="VTE_AbsentMinded", Weight=2, Coupling="Research" },
            new DomainRow{ Domain="Work", TraitDef="VTE_Slob", Weight=2, Coupling="" },
            new DomainRow{ Domain="Work", TraitDef="VTE_Submissive", Weight=1, Coupling="" },
            new DomainRow{ Domain="Life", TraitDef="VTE_CouchPotato", Weight=2, Coupling="" },
            new DomainRow{ Domain="Life", TraitDef="VTE_RefinedPalate", Weight=3, Coupling="Cooking" },
            new DomainRow{ Domain="Life", TraitDef="Gourmet", Weight=2, Coupling="Cooking" },
            new DomainRow{ Domain="Life", TraitDef="VTE_Lush", Weight=3, Coupling="Global" },
            new DomainRow{ Domain="Life", TraitDef="VTE_Stoner", Weight=2, Coupling="" },
            new DomainRow{ Domain="Life", TraitDef="VTE_Groundbreaker", Weight=2, Coupling="Construction" },
            new DomainRow{ Domain="Life", TraitDef="EatingSpeed", Weight=1, Coupling="" },
            new DomainRow{ Domain="Body", TraitDef="VTE_ThickSkinned", Weight=2, Coupling="" },
            new DomainRow{ Domain="Body", TraitDef="VTE_ThinSkinned", Weight=2, Coupling="" },
            new DomainRow{ Domain="Body", TraitDef="VTE_ColdInclined", Weight=2, Coupling="" },
            new DomainRow{ Domain="Body", TraitDef="VTE_HeatInclined", Weight=2, Coupling="" },
            new DomainRow{ Domain="Body", TraitDef="ColdLover", Weight=1, Coupling="" },
            new DomainRow{ Domain="Body", TraitDef="HeatLover", Weight=1, Coupling="" },
            new DomainRow{ Domain="Body", TraitDef="VTE_HeavySleeper", Weight=1, Coupling="" },
            new DomainRow{ Domain="Body", TraitDef="VTE_Insomniac", Weight=2, Coupling="" },
            new DomainRow{ Domain="Body", TraitDef="Nimble", Weight=3, Coupling="Melee" },
            new DomainRow{ Domain="Body", TraitDef="Immunity", Weight=3, Coupling="Medical" },
            new DomainRow{ Domain="Body", TraitDef="Constitution", Weight=2, Coupling="Medical" },
            new DomainRow{ Domain="Body", TraitDef="QuickSleeper", Weight=2, Coupling="" },
            new DomainRow{ Domain="Psy", TraitDef="PsychicSensitivity", Weight=3, Coupling="Psy" },
            new DomainRow{ Domain="Psy", TraitDef="Psychopath", Weight=2, Coupling="" },
            new DomainRow{ Domain="Psy", TraitDef="VTE_Eccentric", Weight=2, Coupling="Research" },
            new DomainRow{ Domain="Psy", TraitDef="Occultist", Weight=2, Coupling="Psy" },
            new DomainRow{ Domain="Psy", TraitDef="VTE_MadSurgeon", Weight=1, Coupling="Medical" },
        };
        // 语义冲突对(跨mod补充语义): 运行时双向注入双方 conflictingTraits
        public static readonly string[][] ConflictPairs = new string[][]
        {
            new string[] { "Ascetic", "VTE_FunLoving" },
            new string[] { "Bloodlust", "Kind" },
            new string[] { "Butcher", "VTE_AnimalLover" },
            new string[] { "Cannibal", "Kind" },
            new string[] { "ColdLover", "VTE_HeatInclined" },
            new string[] { "DeepSleeper", "QuickSleeper" },
            new string[] { "DeepSleeper", "VTE_Insomniac" },
            new string[] { "Extrovert", "Recluse" },
            new string[] { "HeatLover", "VTE_ColdInclined" },
            new string[] { "Kind", "VTE_MadSurgeon" },
            new string[] { "Medic", "VTE_MadSurgeon" },
            new string[] { "NaturalMood", "Neurotic" },
            new string[] { "Perfectionist", "VTE_Slob" },
            new string[] { "VTE_ColdInclined", "VTE_HeatInclined" },
        };
    }
}
