// 由 Source/gen_letter_keys.py 生成,勿手改。维度→slug + 每个文案槽的变体数(供随机取用)。
namespace HSKTraitExt
{
    public static class HSKLetterData
    {
        // 行为维度(与规则表"行为维度"列一致) -> Keyed slug
        public static readonly string[][] CauseSlug = new string[][]
        {
            new string[] { "体质抗病", "immunity" },
            new string[] { "作息-夜行", "nightshift" },
            new string[] { "作息-晨行", "dawnshift" },
            new string[] { "健身", "workout" },
            new string[] { "偷窃", "stealing" },
            new string[] { "冥想", "meditation" },
            new string[] { "击杀人类", "killing" },
            new string[] { "制药/化学", "chemistry" },
            new string[] { "动物", "animals" },
            new string[] { "动物虐待", "animalabuse" },
            new string[] { "医疗", "medicine" },
            new string[] { "压力崩溃", "breakdown" },
            new string[] { "吸烟", "smokeleaf" },
            new string[] { "唯美追求", "artistry" },
            new string[] { "商贸/谈判", "trading" },
            new string[] { "园艺", "gardening" },
            new string[] { "外交", "diplomacy" },
            new string[] { "孤独倾向", "solitude" },
            new string[] { "射击", "shooting" },
            new string[] { "屠宰", "butchery" },
            new string[] { "岩矿", "mining" },
            new string[] { "建造", "construction" },
            new string[] { "情爱", "lovemaking" },
            new string[] { "战后创伤", "trauma" },
            new string[] { "手工/工匠", "handcraft" },
            new string[] { "棋牌", "boardgames" },
            new string[] { "残忍手术", "cruelty" },
            new string[] { "清洁/整洁", "cleaning" },
            new string[] { "温度-耐寒", "coldwork" },
            new string[] { "温度-耐热", "heatwork" },
            new string[] { "烹饪", "cooking" },
            new string[] { "看电视", "television" },
            new string[] { "研究", "research" },
            new string[] { "社交闲聊", "socializing" },
            new string[] { "耐痛/战场", "battlefield" },
            new string[] { "药物滥用", "harddrugs" },
            new string[] { "近战", "melee" },
            new string[] { "进食习惯", "eatingspeed" },
            new string[] { "闪避/肉搏", "dodging" },
            new string[] { "阅读", "reading" },
            new string[] { "音乐演奏", "music" },
            new string[] { "餐饮讲究", "finefood" },
            new string[] { "饮酒", "alcohol" },
            new string[] { "饮食健康", "healthymeals" },
            new string[] { "饮食放纵", "indulgence" },
        };
        // 成因 -> 可用变体套数
        public static readonly string[][] SceneVariants = new string[][]
        {
            new string[] { "alcohol", "4" },
            new string[] { "animalabuse", "4" },
            new string[] { "animals", "4" },
            new string[] { "artistry", "4" },
            new string[] { "boardgames", "4" },
            new string[] { "breakdown", "4" },
            new string[] { "butchery", "4" },
            new string[] { "chemistry", "4" },
            new string[] { "cleaning", "4" },
            new string[] { "coldwork", "4" },
            new string[] { "construction", "4" },
            new string[] { "cooking", "4" },
            new string[] { "cruelty", "4" },
            new string[] { "dawnshift", "4" },
            new string[] { "diplomacy", "4" },
            new string[] { "dodging", "4" },
            new string[] { "eatingspeed", "4" },
            new string[] { "finefood", "4" },
            new string[] { "gardening", "4" },
            new string[] { "handcraft", "4" },
            new string[] { "harddrugs", "4" },
            new string[] { "healthymeals", "4" },
            new string[] { "heatwork", "4" },
            new string[] { "killing", "4" },
            new string[] { "lovemaking", "4" },
            new string[] { "medicine", "4" },
            new string[] { "meditation", "4" },
            new string[] { "melee", "4" },
            new string[] { "mining", "4" },
            new string[] { "music", "4" },
            new string[] { "nightshift", "4" },
            new string[] { "reading", "4" },
            new string[] { "research", "4" },
            new string[] { "shooting", "4" },
            new string[] { "smokeleaf", "4" },
            new string[] { "socializing", "4" },
            new string[] { "stealing", "4" },
            new string[] { "television", "4" },
            new string[] { "trading", "4" },
            new string[] { "workout", "4" },
        };
        // 特性 -> 可用习惯句套数
        public static readonly string[][] HabitVariants = new string[][]
        {
            new string[] { "Aesthete", "4" },
            new string[] { "AnnoyingVoice", "2" },
            new string[] { "Bloodlust", "4" },
            new string[] { "BrownThumb", "4" },
            new string[] { "Butcher", "4" },
            new string[] { "Chemist", "4" },
            new string[] { "ColdLover", "4" },
            new string[] { "Constitution", "4" },
            new string[] { "Diplomat", "4" },
            new string[] { "Dodging", "4" },
            new string[] { "DrugDesire", "4" },
            new string[] { "EatingSpeed", "4" },
            new string[] { "Faith", "2" },
            new string[] { "Gourmet", "4" },
            new string[] { "HSK_Bookworm", "4" },
            new string[] { "HSK_EarlyRiser", "4" },
            new string[] { "HSK_Glutton", "4" },
            new string[] { "HSK_GymRat", "4" },
            new string[] { "HSK_HealthNut", "4" },
            new string[] { "HSK_Meditator", "4" },
            new string[] { "HSK_Musician", "4" },
            new string[] { "HSK_NightOwl", "4" },
            new string[] { "HSK_Tactician", "4" },
            new string[] { "HeatLover", "4" },
            new string[] { "Immunity", "2" },
            new string[] { "Industriousness", "2" },
            new string[] { "Inventor", "4" },
            new string[] { "Jealous", "2" },
            new string[] { "Kind", "4" },
            new string[] { "Medic", "4" },
            new string[] { "NeatFreak", "4" },
            new string[] { "Nimble", "2" },
            new string[] { "Occultist", "2" },
            new string[] { "PainThreshold", "4" },
            new string[] { "Perfectionist", "4" },
            new string[] { "PsychicSensitivity", "2" },
            new string[] { "Psychopath", "2" },
            new string[] { "QuickSleeper", "2" },
            new string[] { "Recluse", "4" },
            new string[] { "Rockhound", "4" },
            new string[] { "ShootingAccuracy", "4" },
            new string[] { "Tough", "2" },
            new string[] { "Trader", "4" },
            new string[] { "VTE_AbsentMinded", "2" },
            new string[] { "VTE_AnimalHater", "4" },
            new string[] { "VTE_AnimalLover", "4" },
            new string[] { "VTE_Anxious", "2" },
            new string[] { "VTE_Brave", "2" },
            new string[] { "VTE_Clumsy", "2" },
            new string[] { "VTE_ColdInclined", "2" },
            new string[] { "VTE_CouchPotato", "4" },
            new string[] { "VTE_Coward", "2" },
            new string[] { "VTE_Desensitized", "4" },
            new string[] { "VTE_DrunkenMaster", "2" },
            new string[] { "VTE_Eccentric", "2" },
            new string[] { "VTE_FunLoving", "2" },
            new string[] { "VTE_Groundbreaker", "4" },
            new string[] { "VTE_HeatInclined", "2" },
            new string[] { "VTE_HeavySleeper", "2" },
            new string[] { "VTE_Insatiable", "4" },
            new string[] { "VTE_Insomniac", "2" },
            new string[] { "VTE_IronStomach", "2" },
            new string[] { "VTE_Kleptomaniac", "4" },
            new string[] { "VTE_Lush", "4" },
            new string[] { "VTE_MadSurgeon", "4" },
            new string[] { "VTE_MartialArtist", "4" },
            new string[] { "VTE_Prodigy", "2" },
            new string[] { "VTE_Prude", "2" },
            new string[] { "VTE_RefinedPalate", "2" },
            new string[] { "VTE_Slob", "2" },
            new string[] { "VTE_Snob", "2" },
            new string[] { "VTE_Stoner", "4" },
            new string[] { "VTE_Submissive", "2" },
            new string[] { "VTE_ThickSkinned", "2" },
            new string[] { "VTE_ThinSkinned", "2" },
            new string[] { "VTE_Tycoon", "2" },
            new string[] { "VTE_Vengeful", "2" },
            new string[] { "VTE_Wanderlust", "2" },
            new string[] { "VTE_Workaholic", "2" },
            new string[] { "VTE_WorldWeary", "4" },
            new string[] { "Wimp", "2" },
        };
        public const int FrameCount = 4;
        public static readonly string[] FrameHeads = new string[]
        {
            "HSKTrait.FrameHead.1",
            "HSKTrait.FrameHead.2",
            "HSKTrait.FrameHead.3",
            "HSKTrait.FrameHead.4",
        };
        public static readonly string[][] FrameSceneVariants = new string[][]
        {
            new string[] { "1", "4" },
            new string[] { "2", "4" },
            new string[] { "3", "4" },
            new string[] { "4", "4" },
        };
        public const int ExitVariants = 4;
        public const int AbstainVariants = 4;
    }
}
