<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutDir>..\..\1.6\Assemblies\</OutDir>
		<Copyright>Copyright (c) 2026 Bradson</Copyright>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DefineConstants>DEBUG;V1_5;V1_6</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DefineConstants>V1_5;V1_6</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*" />
		<PackageReference Include="Lib.Harmony" Version="2.3.*" ExcludeAssets="runtime" />
		<Publicize Include="mscorlib:System.Collections.Generic.Dictionary`2._buckets" />
		<Publicize Include="mscorlib:System.Collections.Generic.Dictionary`2._entries" />
	</ItemGroup>
</Project>
